import {STAGE_INFO} from './levels';
import type {SaveData} from './types';

export const text=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function icon(name:'jump'|'strike'|'dodge'|'pause'|'seal'|'full') {
  const paths={jump:'M5 18 12 5l7 13M7 14h10',strike:'m6 20 3-5 9-11 2 2-11 9-5 3m2-5 5 5',dodge:'M4 14c3-7 12-8 16-2m-5-6 5 6-7 1M3 19h9',pause:'M8 5v14M16 5v14',seal:'M12 3 20 8v8l-8 5-8-5V8zm0 4 4 5-4 5-4-5z',full:'M4 9V4h5m6 0h5v5M4 15v5h5m6 0h5v-5'};
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="square" aria-hidden="true"><path d="${paths[name]}"/></svg>`;
}
export function titleScreen(save:SaveData,fullscreen:string,exit:string) {
  const entries=[[save.unlocked>1?'Continue':'Enter the crypt','start'],['Chapters','chapters'],['Journal','journal'],['Settings','settings']];
  return `<section class="title-screen" aria-label="Main menu"><header class="title-brand"><svg class="title-mark" viewBox="0 0 80 64" fill="none" aria-hidden="true"><path d="M54 8a25 25 0 1 0 1 45M49 10a22 22 0 0 0 0 41M39 10l-6 42M46 13l-6 35"/><path d="m18 53 5-4m35-1 5 4"/></svg><h1 aria-label="MOONPAW">M<span class="moon-letter">O</span><span class="moon-letter second-moon">O</span>NPAW</h1><div class="title-sub"><i></i><span>ASHEN VOW</span><i></i></div></header><nav class="vow-menu" aria-label="Main menu">${entries.map(([label,action])=>`<button data-action="${action}" aria-label="${label}"><span class="menu-word">${label}</span></button>`).join('')}</nav><div class="title-bottom"><button data-action="credits">Credits</button>${fullscreen}${exit}</div><p class="title-credit">Adnan Naous <span aria-hidden="true">&middot;</span> <span class="version">0.6.0</span></p></section>`;
}
export function journeyScreen(save:SaveData,selected:number) {
  const stage=STAGE_INFO[selected],col=selected%2,row=Math.floor(selected/2),completed=save.best[stage.id];
  return `<div class="sheet-heading"><h2>Chapters</h2></div><div class="journey"><nav class="journey-route" aria-label="Chapter selection">${STAGE_INFO.map((s,i)=>`<button data-stage="${i}" data-preview="${i}" ${i>=save.unlocked?'disabled':''} aria-current="${i===selected?'step':'false'}"><span class="chapter-dot" aria-hidden="true"></span><span class="chapter-number">${String(i+1).padStart(2,'0')}</span><span><strong>${text(s.name)}</strong><small>${i>=save.unlocked?'Locked':save.best[s.id]?'Completed':''}</small></span><span class="chapter-state" aria-hidden="true">${save.best[s.id]?'&#9670;':i>=save.unlocked?'&#8212;':''}</span></button>`).join('')}</nav><article class="journey-detail"><div class="journey-art" style="background-position:${col*100}% ${row*25}%"><span>${String(selected+1).padStart(2,'0')}</span></div><p class="eyebrow">${text(stage.subtitle)}</p><h3>${text(stage.name)}</h3><p>${text(stage.description)}</p><div class="journey-facts"><span>3 sealed encounters</span><span>2 lost names</span></div>${completed?`<p class="quiet">Best crossing: ${Math.floor(completed.time/60)}:${String(Math.floor(completed.time%60)).padStart(2,'0')} · ${completed.deaths} deaths</p>`:''}</article></div>`;
}
