import {STAGE_INFO} from './levels';
import type {SaveData} from './types';

export const text=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function icon(name:'jump'|'strike'|'dodge'|'pause'|'seal'|'full') {
  const paths={jump:'M5 18 12 5l7 13M7 14h10',strike:'m6 20 3-5 9-11 2 2-11 9-5 3m2-5 5 5',dodge:'M4 14c3-7 12-8 16-2m-5-6 5 6-7 1M3 19h9',pause:'M8 5v14M16 5v14',seal:'M12 3 20 8v8l-8 5-8-5V8zm0 4 4 5-4 5-4-5z',full:'M4 9V4h5m6 0h5v5M4 15v5h5m6 0h5v-5'};
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="square" aria-hidden="true"><path d="${paths[name]}"/></svg>`;
}
export function titleScreen(save:SaveData,fullscreen:string,exit:string) {
  const index=save.unlocked-1,chapter=STAGE_INFO[index];
  const entries=[['01',save.unlocked>1?'Continue':'Enter the crypt','start','Take up the unfinished vow'],['02','Chapters','chapters','Trace the ten thresholds'],['03','Journal','journal','Read what survived'],['04','Settings','settings','Sound · display · controls']];
  return `<section class="title-screen" aria-label="Main menu"><div class="title-kicker"><span class="fine-rule"></span><span>ADNAN NAOUS PRESENTS</span></div><h1>MOONPAW</h1><div class="title-sub"><span>ASHEN VOW</span><i></i></div><p class="premise">The city stole your name.<br>Make it remember.</p><nav class="vow-menu" aria-label="Main menu">${entries.map(([number,label,action,detail])=>`<button data-action="${action}" aria-label="${label}"><span class="menu-number">${number}</span><span class="menu-word">${label}<small>${detail}</small></span><span class="menu-arrow" aria-hidden="true">↗</span></button>`).join('')}</nav><div class="title-bottom"><button data-action="credits">Credits</button>${fullscreen}${exit}<span class="version">0.4.0</span></div><div class="title-record"><span>${icon('seal')}</span><p><small>YOUR NEXT THRESHOLD · ${String(index+1).padStart(2,'0')}</small>${text(chapter.name)}</p></div></section><aside class="title-world-caption" aria-hidden="true"><span>THE NAMELESS TRAVELER</span><p>A blade of borrowed iron.<br>A vow that will not die.</p><i></i></aside>`;
}
export function journeyScreen(save:SaveData,selected:number) {
  const stage=STAGE_INFO[selected],col=selected%2,row=Math.floor(selected/2),completed=save.best[stage.id];
  return `<div class="sheet-heading"><p class="eyebrow">A CITY BUILT TO FORGET</p><h2>Ten thresholds</h2><p class="quiet">Each door changes the rules. Carry every name beyond it.</p></div><div class="journey"><nav class="journey-route" aria-label="Chapter selection">${STAGE_INFO.map((s,i)=>`<button data-stage="${i}" data-preview="${i}" ${i>=save.unlocked?'disabled':''} aria-current="${i===selected?'step':'false'}"><span class="chapter-dot" aria-hidden="true"></span><span class="chapter-number">${String(i+1).padStart(2,'0')}</span><span><strong>${text(s.name)}</strong><small>${i>=save.unlocked?'Unreached':save.best[s.id]?'Crossed':text(s.subtitle)}</small></span><span class="chapter-state" aria-hidden="true">${save.best[s.id]?'✓':i>=save.unlocked?'—':'↗'}</span></button>`).join('')}</nav><article class="journey-detail"><div class="journey-art" style="background-position:${col*100}% ${row*25}%"><span>${String(selected+1).padStart(2,'0')}</span></div><p class="eyebrow">${text(stage.subtitle)}</p><h3>${text(stage.name)}</h3><p>${text(stage.description)}</p><div class="journey-facts"><span>3 sealed encounters</span><span>2 lost names</span></div>${completed?`<p class="quiet">Best crossing: ${Math.floor(completed.time/60)}:${String(Math.floor(completed.time%60)).padStart(2,'0')} · ${completed.deaths} deaths</p>`:'<p class="quiet">A pact waits beyond the first encounter.</p>'}</article></div>`;
}
